#!/bin/sh

# this script might be very unoptimized but im not sure
counter=0
wifi="unknown"
battery="unknown"
disk="unknown"
ram="unknown"
bluetooth="unknown"

while true; do
current_time=$(date +'%Y-%m-%d %H:%M:%S')
ram=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{if ($3 == "[MUTED]") print "MUTED"; else print $2 * 100 "%"}')

if [ $((counter % 5)) -eq 0 ]; then
    battery=$(acpi -b | sed -E 's/Battery [0-9]+: //; s/, remaining//; s/, until charged//' | sed -E 's/,/:/; s/,/   /')

    bt_name=$(bluetoothctl devices Connected | awk '{$1=$2=""; print substr($0,3)}')
    if [ -z "$bt_name" ]; then
            bluetooth="Disconnected"
    else
            bluetooth="$bt_name"
    fi
fi

if [ $((counter % 25)) -eq 0 ]; then
    wifi=$(nmcli -t -f DEVICE,STATE device | awk -F: '$1=="wlo1" {print $2}')
    disk=$(df -h | grep '/dev/nvme0n1p3' | awk '{printf "Free: %s  Used: %s", $4, $3}')
fi

cpu=$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8"%"}')

act=$(cat /sys/class/drm/card1/gt_act_freq_mhz 2>/dev/null || echo 0)
max=$(cat /sys/class/drm/card1/gt_max_freq_mhz 2>/dev/null || echo 1)
gpu=$((act * 100 / max))%

echo "CPU: $cpu    GPU: $gpu    Wifi: $wifi    BT: $bluetooth    Mem: $ram    $disk    Vol: $volume    $battery    $current_time"

counter=$((counter + 1))
sleep 0.1
done
